name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

   - name: install build dependencies
      run: sudo apt-get install libboost-dev
      
    - name: Build
      run: |
          cmake -S . -B build
          cmake --build build
          cd build && ctest --output-on-failure

    - name: Upload Test Artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-logs
        path: build/Testing/Temporary
